# Introduccion a la programacion para la ciencia de datos

La ciencia de datos permite hacer innumerables aplicaciones en su mayoría basadas en estadistica, programacion, visualizaciones y modelos que representan sistemas dinamicos, y para ello tendremos que plasmar dicha realidad en datos, y porteriormente darle un sentido matematico, a continuacion veremos el modulo `Numpy` el cual es una herramienta que nos permite hacer eso

# Modulo Numpy

<img src = "numpy_logo.png" height = "280" width = "280">

Numpy es un paquete fundamental para el trabajo científico en python:

* Contiene Funciones, módulos, clases y cierto tipo especial de datos. 
* Permite el manejo de Arrays Multidimensionales. 
* Contiene Funciones sofisticadas y optimizadas.
* Contiene un paquete de álgebra lineal y permite hacer cálculos estadísticos, ajustes, interpolación entre otras.


> El tipo de dato mas importante en numpy es el **array**. El array es un tipo de dato, formado a partir de otro tipo de datos mas sencillos y que estan ordenados en una secuencia definida, en ese sentido es muy similar a una lista o tupla, pero a diferencia de estos, un array solo admite un tipo de dato.

- Consultar documentación: https://numpy.org/

## Crear un array

Un array puede ser creado mediante el uso de datos nativos de python (listas, tuplas,datos
básicos) usando la función **numpy.array()**:

```python
numpy.array(object, dtype=None)
```
Donde podemos especificar el tipo de datos con *dtype*, el orden con *order* (esto hace referencia el modo "C", por filas, o "F", por columnas, para el diseño de memoria del arreglo. Generalmente se deja en "K" para que automaticamente escoja la mejor opción), la dimensión miníma puede establecerse con con *ndmin*.

In [1]:
import numpy as np

In [4]:
lista = [1, 2, 3, 4, 5]
arreglo = np.array(lista)
arreglo

array([1, 2, 3, 4, 5])

In [5]:
lista = [1,"2", 3, 4, 5]
arreglo = np.array(lista)
arreglo

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [6]:
lista = [True, False]
arreglo = np.array(lista)
arreglo

array([ True, False])

## Arrays de mas de una dimension

Es importante observar que los arrays pueden tener tanto filas como columnas queramos

In [12]:
numeros = [[1, 2, 3, 4, 5.0]]
np.array(numeros, dtype = int)

array([[1, 2, 3, 4, 5]])

In [16]:
numeros = [[1, 2, 3, 4, 5.0], 
           [6, 7, 8, 9, 10]]

np.array(numeros, dtype = float)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.]])

In [17]:
numeros = [[1, 2, 3, 4, 5.0], 
           [6, 7, 8, 9, 10],
           [11,12,13,14,15]]

np.array(numeros, dtype = float)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [18]:
np.array([[1, 2, 3, 4, 5.0], 
           [6, 7, 8, 9, 10],
           [11,12,13,14,15]], dtype = float)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

## Atributos de un array

Los arrays pueden tener diferentes atributos, estos son algunos de los mas comunes:

- `shape`, `size`, `dtype`, `nbytes`

In [41]:
matriz = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11,12,13,14,15]]

matriz = np.array(matriz, dtype = "int8")

### Atributo shape

In [33]:
matriz.shape

(3, 5)

### Atributo size

In [34]:
matriz.size

15

### Atributo dtype

In [35]:
matriz.dtype

dtype('int64')

In [36]:
type(matriz)

numpy.ndarray

### Atributo nbytes

In [42]:
matriz.nbytes

15

## Algunos metodos

Los métodos de un array nos permiten realizar algunas de sus funcionalidades como veremos acontinuación:

### Metodo transpose()

In [ ]:
matriz = [[1, 2, 3, 4, 5], 
          [6, 7, 8, 9, 10],
          [11,12,13,14,15]]

matriz = np.array(matriz, dtype = "int8")

In [43]:
matriz.transpose()

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]], dtype=int8)

In [44]:
matriz.T

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]], dtype=int8)

### Metodo arange()

In [46]:
array_numerico = np.arange(1, 100)
array_numerico

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [55]:
array_numerico = np.arange(start = 1, stop = 100)
array_numerico

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [56]:
array_numerico.size

99

### Metodo linspace

In [60]:
array_numerico = np.linspace(start = 1, stop = 100, num = 100)
array_numerico

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [58]:
array_numerico.size

50

### Metodo random.rand()

In [97]:
array_aleatorio = np.random.rand(5, 3)*100
array_aleatorio

array([[51.58026893, 70.00640093, 75.5743815 ],
       [22.40369425, 57.60387734, 44.86557995],
       [31.60982859, 23.64723018, 27.14036401],
       [27.87446447, 73.23840218, 85.58925603],
       [24.94677268, 75.24007715, 57.36121977]])

### Metodo randint

In [132]:
array_aleatorio = np.random.randint(2, size = (5, 3))
array_aleatorio

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0],
       [0, 1, 1],
       [0, 0, 1]])

### Metodo ones()

In [135]:
array_ones = np.ones(shape = (10, 10))
array_ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Metodo zeros()

In [136]:
array_ones = np.zeros(shape = (10, 10))
array_ones

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

### Metodo identity()

In [139]:
np.identity(5, dtype = int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

### Metodo random.uniform()

In [141]:
np.random.uniform(1, 100, 100)

array([ 1.95681518, 19.88185684,  1.50590124, 44.47044625, 90.42855978,
       61.55208793, 76.80026254, 28.32487197, 54.27267234, 58.70187176,
       37.27056125, 32.62564175, 82.03032552, 87.80947592, 56.78880997,
       74.2364174 , 48.56103781, 71.94877493, 76.09505173, 19.86496649,
       30.11696764, 68.41570576, 67.42788003, 13.19087994, 84.9042707 ,
       93.52732819, 90.68404746, 77.17419814, 56.43574976, 54.50224477,
       45.62247075, 97.67600132, 94.38707535, 35.5576584 , 55.64180562,
       62.19619428, 86.3170005 , 20.8967523 ,  1.95029518, 95.94015287,
       17.90710695, 17.87101948,  2.66070038,  3.60342726, 45.06359919,
       80.44519944, 17.26660113, 30.65376511, 90.4949914 , 36.94568356,
       45.07621694,  4.24574099, 64.14775077, 28.04977361, 28.9046859 ,
        9.55051526,  3.32335911, 65.03637248, 82.55962775, 21.65403982,
       18.40513242, 54.80911792, 13.14434815, 70.34009408, 66.61709739,
       30.10662312, 20.13869058, 73.94983535, 39.6551674 , 49.75

### Metodo copy()

In [147]:
x = [1,2,3,4]
x

[1, 2, 3, 4]

In [148]:
y = x

In [149]:
y

[1, 2, 3, 4]

In [153]:
x.append(10)

In [151]:
x

[1, 2, 3, 4, 10]

In [152]:
y

[1, 2, 3, 4, 10]

In [161]:
z = [1,2,3,34,4,3454556]
z

[1, 2, 3, 34, 4, 3454556]

In [162]:
w = z.copy()

In [163]:
w

[1, 2, 3, 34, 4, 3454556]

In [164]:
z.remove(1)

In [165]:
z

[2, 3, 34, 4, 3454556]

In [166]:
w

[1, 2, 3, 34, 4, 3454556]

In [167]:
array_ones = np.ones(shape = (10, 10))
array_ones_new = array_ones.copy()
array_ones_new

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])